### ISSUE TITLE
WinCompose 0.8.1 is available

### ISSUE THREAD

**Issue by Mikaela** [ktos/chocolatey-packages#1]
* https://github.com/samhocevar/wincompose/releases/tag/v0.8.1

Thanks for maintaining the package. I have been watching the WinCompose icon warn about a new update for a few days and thought that I could contact you just in case.

**Comment by ktos** [comment]
Thank you very much! I've seen the notification about this update but completely forgot to update the package.

Just pushed for approval (fixed in 24c2781e9224ec31cf4a272417b8e6a73fcc8374) so it should be live in a few hours.
